2024-11-15 20:15:24,553 | MainProcess | MainThread | docker.utils.config | DEBUG | Trying paths: ['/Users/ctavolazzi/.docker/config.json', '/Users/ctavolazzi/.dockercfg']
2024-11-15 20:15:24,553 | MainProcess | MainThread | docker.utils.config | DEBUG | Found file at path: /Users/ctavolazzi/.docker/config.json
2024-11-15 20:15:24,554 | MainProcess | MainThread | docker.auth | DEBUG | Found 'credsStore' section
2024-11-15 20:15:24,571 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /version HTTP/1.1" 200 None
2024-11-15 20:15:24,579 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /v1.44/images/python:3-slim/json HTTP/1.1" 404 None
2024-11-15 20:15:24,579 | MainProcess | MainThread | root | INFO | Pulling image python:3-slim...
2024-11-15 20:15:24,579 | MainProcess | MainThread | docker.auth | DEBUG | Looking for auth config
2024-11-15 20:15:24,579 | MainProcess | MainThread | docker.auth | DEBUG | Using credentials store "desktop"
2024-11-15 20:15:24,580 | MainProcess | MainThread | docker.auth | DEBUG | Looking for auth entry for 'https://index.docker.io/v1/'
2024-11-15 20:15:24,693 | MainProcess | MainThread | docker.auth | DEBUG | Found auth config
2024-11-15 20:15:30,790 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "POST /v1.44/images/create?tag=3-slim&fromImage=python HTTP/1.1" 200 None
2024-11-15 20:15:39,399 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /v1.44/images/python:3-slim/json HTTP/1.1" 200 None
2024-11-15 20:15:39,702 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "POST /v1.44/containers/create?name=autogen-code-exec-978dcd21-1ce8-43cf-8e2b-841d6a8c0ac3 HTTP/1.1" 201 None
2024-11-15 20:15:39,719 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /v1.44/containers/a7fe12c4e3256a68f1e3e7dff4368981d9ad3586aba83bfbe1e28c5672501984/json HTTP/1.1" 200 None
2024-11-15 20:15:40,156 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "POST /v1.44/containers/a7fe12c4e3256a68f1e3e7dff4368981d9ad3586aba83bfbe1e28c5672501984/start HTTP/1.1" 204 0
2024-11-15 20:15:40,263 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /v1.44/containers/a7fe12c4e3256a68f1e3e7dff4368981d9ad3586aba83bfbe1e28c5672501984/json HTTP/1.1" 200 None
2024-11-15 20:15:40,265 | MainProcess | MainThread | root | INFO | Setting up agents
2024-11-15 20:15:40,266 | MainProcess | MainThread | AutogenGame | ERROR | Fatal error: ConversableAgent.__init__() got an unexpected keyword argument 'callback'
2024-11-15 20:15:40,273 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /v1.44/containers/autogen-code-exec-978dcd21-1ce8-43cf-8e2b-841d6a8c0ac3/json HTTP/1.1" 200 None
2024-11-15 20:15:50,457 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "POST /v1.44/containers/a7fe12c4e3256a68f1e3e7dff4368981d9ad3586aba83bfbe1e28c5672501984/stop HTTP/1.1" 204 0
