2024-11-15 20:23:20,251 | MainProcess | MainThread | docker.utils.config | DEBUG | Trying paths: ['/Users/ctavolazzi/.docker/config.json', '/Users/ctavolazzi/.dockercfg']
2024-11-15 20:23:20,251 | MainProcess | MainThread | docker.utils.config | DEBUG | Found file at path: /Users/ctavolazzi/.docker/config.json
2024-11-15 20:23:20,251 | MainProcess | MainThread | docker.auth | DEBUG | Found 'credsStore' section
2024-11-15 20:23:20,266 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /version HTTP/1.1" 200 None
2024-11-15 20:23:20,272 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /v1.44/images/python:3-slim/json HTTP/1.1" 200 None
2024-11-15 20:23:20,311 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "POST /v1.44/containers/create?name=autogen-code-exec-393f3c93-d334-41f1-a24e-e00222e88c20 HTTP/1.1" 201 None
2024-11-15 20:23:20,319 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /v1.44/containers/b848ce9b8a8ea52a087a2ac8e2e397d8f05ff275d2fa69b6a297fdee673e7b3a/json HTTP/1.1" 200 None
2024-11-15 20:23:20,583 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "POST /v1.44/containers/b848ce9b8a8ea52a087a2ac8e2e397d8f05ff275d2fa69b6a297fdee673e7b3a/start HTTP/1.1" 204 0
2024-11-15 20:23:20,689 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /v1.44/containers/b848ce9b8a8ea52a087a2ac8e2e397d8f05ff275d2fa69b6a297fdee673e7b3a/json HTTP/1.1" 200 None
2024-11-15 20:23:20,690 | MainProcess | MainThread | AutogenGame | INFO | Setting up agents
2024-11-15 20:23:20,691 | MainProcess | MainThread | httpx | DEBUG | load_ssl_context verify=True cert=None trust_env=True http2=False
2024-11-15 20:23:20,691 | MainProcess | MainThread | httpx | DEBUG | load_verify_locations cafile='/Users/ctavolazzi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/certifi/cacert.pem'
2024-11-15 20:23:20,703 | MainProcess | MainThread | AutogenGame | INFO | Starting Autogen CYOA game
2024-11-15 20:23:20,704 | MainProcess | MainThread | AutogenGame | ERROR | Error during game execution: AutogenGame.setup_agents.<locals>.<lambda>() takes 2 positional arguments but 4 were given
2024-11-15 20:23:20,709 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "GET /v1.44/containers/autogen-code-exec-393f3c93-d334-41f1-a24e-e00222e88c20/json HTTP/1.1" 200 None
2024-11-15 20:23:30,875 | MainProcess | MainThread | urllib3.connectionpool | DEBUG | http://localhost:None "POST /v1.44/containers/b848ce9b8a8ea52a087a2ac8e2e397d8f05ff275d2fa69b6a297fdee673e7b3a/stop HTTP/1.1" 204 0
2024-11-15 20:23:30,876 | MainProcess | MainThread | AutogenGame | ERROR | Fatal error: AutogenGame.setup_agents.<locals>.<lambda>() takes 2 positional arguments but 4 were given
